### ISSUE TITLE
How long does it take to generate one second of audio? Is it possible to use it on android or ios client to do inference?

### ISSUE THREAD

**Issue by KevinYuk** [tomlepaine/fast-wavenet#11]
As is kown,
For a downsized model (4000hz vs 16000 sampling rate, 16 filters v/s 256, 2 stacks vs ??):

A Tesla K80 needs around ~4 minutes to generate one second of audio.
A recent macbook pro needs around ~15 minutes. Deepmind has reported that generating one second of audio with their model takes about 90 minutes.

**Comment by tomlepaine** [comment]
Thanks for the numbers @KevinYuk. If you want to try to get it working on Andriod, maybe start [here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android). I've never used tensorflow on android myself.
