### ISSUE TITLE
Can someone please share a pretrained model 

### ISSUE THREAD

**Issue by ishandutta2007** [tomlepaine/fast-wavenet#21]
Preferably on LJSpeech dataset.

**Comment by tomlepaine** [comment]
[This repo](https://github.com/twidddj/tf-wavenet_vocoder) seems to have what you are looking for.

**Comment by ishandutta2007** [comment]
That is of that repo not this repo, please keep the ticket open for someone to share it.

**Comment by ishandutta2007** [comment]
Please keep this issue open, if you are not actively working on it, no issues, you can take it as no obligations for you, let the open-source community respond and decide its course.
